beaver.annotation:
    resource: '@BackendBundle/Controller'
    type: annotation

content.routes:
    resource: '@ContentBundle/Resources/config/routing.yml'

beaver:security:
    resource: '@BackendBundle/Resources/config/routes/security.yml'

logout:
    path: /logout

backend.page:
    prefix: /ajax
    resource: 'routes/page.ajax.yml'

backend.block:
    prefix: /ajax
    resource: 'routes/block.ajax.yml'

backend.widgets:
    prefix: /ajax
    resource: 'routes/widget.ajax.yml'

backend:
    resource: 'routes/routing.yml'