beaver.ajax.image.upload:
    path:       /gallery/image
    methods:    [POST]
    controller: Beaver\BackendBundle\Controller\Rest\GalleryController::upload
    condition: 'request.isXmlHttpRequest()'
    options:
        expose: true

beaver.ajax.image.delete:
    path:       /gallery/image
    methods:    [DELETE]
    controller: Beaver\BackendBundle\Controller\Rest\GalleryController::delete
    condition: 'request.isXmlHttpRequest()'
    options:
        expose: true

